# Generated by Django 3.2.7 on 2021-09-03 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complex_queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='competition',
            name='is_win',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
